### ISSUE TITLE
Feature Request: escape `$$`

### ISSUE THREAD

**Issue by nicknovitski** [a8m/envsubst#13]
Thank you so much for this project, the `-no-unset` option was exactly what I was looking for, I've immediately replaced our usage of gettext with it.

Now that I'm a user, would it be possible for envsubst to replace all strings `$$foo` with `$foo`?

In my case, I have kubernetes templates for nginx configuration, which I template with some values, but which also contain nginx variables like `$remote_user` and `$bytes_sent` strings.  My current choices are either to not use `-no-unset`, or (what I actually do) implement my own escaping with sed.

**Comment by a8m** [comment]
Hey @nicknovitski, Thanks for your feedback. I'm glad you find it useful.

I agree that this feature is necessary, but I'm not sure if I prefer `\` or `$` for escaping. I would like to see what other people think about it.

**Comment by tshak** [comment]
I like double dollar (`$${escape_me}`). This is how [terraform templates](https://www.terraform.io/docs/providers/template/d/file.html#inline-templates) works as well.

**Comment by a8m** [comment]
Closing via v1.1.0. Thanks
