### ISSUE TITLE
Escaping syntax

### ISSUE THREAD

**Issue by strowi** [a8m/envsubst#15]
Hi,

nice little helper tool;) Although i recently stumbled over a problem i couldn't find a solution to.. How can i escape sth. like this:
```
A=${static}
```
I know about $${static} -> $static. But what if i need the {} ?

regards,
Roman

**Comment by strowi** [comment]
Ok, 5min. after posting + some fresh air i found a solution.. it seems ${variable.name} will also be ignored.
Not shure thou if that is intended? If so, ignore this pls..;)

**Comment by a8m** [comment]
Hey @strowi, thanks for opening this issue. All you need to do is to add a `$` before the expression. For example:
```console
$ echo 'hello $${HOME}' | envsubst

hello ${HOME}
```

I'm going to close this issue since it works as expected. But, feel free to open it if you have any trouble with it.
