### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by prein** [a8m/envsubst#17]
Would you mind providing a windows binary for download? We use envsubst as a commandline tool in my team and several guys are on windows.

**Comment by a8m** [comment]
Hey, thanks for opening this issue. I uploaded a binary for Windows and it's available under [releases] or [here][release]. Would you mind adding to the README the installation instructions for Windows?

I definitely should start using brew and choco for package management. 

[releases]: https://github.com/a8m/envsubst/releases
[release]: https://github.com/a8m/envsubst/releases/download/v1.1.0/envsubst.exec

**Comment by prein** [comment]
Hi, thanks for providing the binary. Did you mean the extension to be .exec and not .exe?
I have opened a PR with the README update. I hope it looks OK. I'm not a Windows guy myself, but I think it's enough to say "download the exe". Using choco or brew would add convenience of course.

**Comment by a8m** [comment]
PR merged. 

> Hi, thanks for providing the binary. Did you mean the extension to be .exec and not .exe?

I'm not a Windows guy too. I just followed the instructions [here](https://github.com/golang/go/wiki/WindowsCrossCompiling).

**Comment by prein** [comment]
So I guess _.exec_ is a typo, as typically it would be _.exe_ and the instructions you have used also use _.exe_ extension.

**Comment by a8m** [comment]
Oops, I missed that. It should be good now, thanks!

**Comment by stevehipwell** [comment]
Could we get a Windows build? It would be great if I could make this available via Scoop.
