### ISSUE TITLE
Need a simple way to escape dollar symbols

### ISSUE THREAD

**Issue by dexterp** [a8m/envsubst#27]
There needs to be a way to insert dollar symbols in a template Instead of creating a variable (E.G. `DOLLAR=\$`).

For instance if envsubst was used in a bash script, replacing all the dollars $ with a variable will be messy.

**Comment by dexterp** [comment]
Withdrawn, seems to be already available with $$.

**Comment by petrciml** [comment]
Hello @dexterp, your solution seems to be not correct:

At version gettext (0.22.3-r0) (Alpine 3.19)

Input JSON
```JSON
...
"transforms.flatten.type": "org.apache.kafka.connect.transforms.Flatten$$Value",
...
```

Output
```JSON
"transforms.flatten.type": "org.apache.kafka.connect.transforms.Flatten$",
```

I need to preserve also the "Value" part of string in output.
Do you have any help?
