### ISSUE TITLE
ARM/aarch64 release builds?

### ISSUE THREAD

**Issue by rdelfin** [a8m/envsubst#28]
Is there any change aarch64 builds could get added here? Would make porting things like docker images a lot easier!

**Comment by apenney** [comment]
I whipped up #33 for building arm releases, should make it easier to spit out binaries for whatever arch is required!

**Comment by a8m** [comment]
Done. Thanks for the reminder. 

https://github.com/a8m/envsubst/releases/tag/v1.2.0
