### ISSUE TITLE
Replaces $1, $2 etc, which are not environment variables

### ISSUE THREAD

**Issue by Martin4R** [a8m/envsubst#38]
Expressions like $1 get replaced with an empty string, but $1 is by definition no environment variable, because it starts with a digit (See https://stackoverflow.com/a/2821183). 
This behavior is unexpected different compared to the original gnu envsubst, which does not replace $1.

**Comment by a8m** [comment]
Thanks for reporting this, @Martin4R. Feel free to send a patch to fix this, or I can do it sometime this week.

**Comment by a8m** [comment]
Fixed with https://github.com/a8m/envsubst/pull/39
