### ISSUE TITLE
Regression for single-letter variables surrounded with curly braces

### ISSUE THREAD

**Issue by qbarrand** [a8m/envsubst#43]
We observe that the `A=AAA` replacement does not work with `${A}` in 1.4.0.
`$A` does work, and so does `$BB` / `${BB}` with `BB=BBB`.

Reproduction in the Go playground: https://go.dev/play/p/aU2K_t0SrZz

**Comment by a8m** [comment]
Thanks for reporting this, @qbarrand. I'll give this a look

**Comment by neiser** [comment]
@a8m Oh, probably introduced by my change in the lexer?

**Comment by a8m** [comment]
> @a8m Oh, probably introduced by my change in the lexer? Let me have a quick look!

Maybe. Give it a look, please? Thanks

**Comment by neiser** [comment]
@a8m See #45 Includes a reproducer test case which is fixed by the change.

**Comment by neiser** [comment]
@qbarrand Thanks for reporting and also sorry for causing that trouble. Removed one bug, introduced another :see_no_evil:

**Comment by qbarrand** [comment]
@neiser the quick fix much appreciated. Thank you both!

**Comment by a8m** [comment]
Thanks for reporting this, @qbarrand 🙏
