### ISSUE TITLE
Output of 'Release Binaries' workflow differs from past releases 

### ISSUE THREAD

**Issue by AdrianMiska** [a8m/envsubst#46]
Hi, just a heads up:

It seems that the 1.4.1 release is the first one to use a GitHub action to attach assets, and as a result, the installation procedure described in the Readme is no longer applicable (the binaries are now in tar.gz format and have different names).

I just wanted to bring it to your attention in case it was an oversight. I would suggest either updating the Readme to reflect these changes or altering the binaries.yml workflow so that the binaries are not zipped.

**Comment by a8m** [comment]
Thanks for reporting this, @AdrianMiska. Would you like to contribute this change?

cc @apenney.

**Comment by AdrianMiska** [comment]
Thanks for approving my PR!
I just tested and can confirm that 
```
curl -L https://github.com/a8m/envsubst/releases/download/v1.4.2/envsubst-`uname -s`-`uname -m` -o envsubst
chmod +x envsubst 
./envsubst -help
```
is working again on both my Mac and Linux machines.

**Comment by a8m** [comment]
Thanks for your contribution, @AdrianMiska 🙏🏻
