### ISSUE TITLE
Extend supported syntax to get feature parity with drone/envsubst?

### ISSUE THREAD

**Issue by guettli** [a8m/envsubst#54]
Hi,

cluster-api is thinking about switching from drone/envsubst to your implementation:

https://github.com/kubernetes-sigs/cluster-api/issues/8325

The drone/envsubst implementation supports ways which are not supported by your implementation yet.

https://github.com/drone/envsubst#supported-functions

Would you accept PRs to get feature parity?

**Comment by a8m** [comment]
Hey, @guettli 👋 
Sure, feel free to create a separate PR for each functionality and add me as a reviewer.

**Comment by guettli** [comment]
I see that you support variable substitution without curly braces (for example `$HOME`). This would break the current usage. At the moment we only support for example `${HOME}`.

Sorry, this means we can't use your library.
